### ISSUE TITLE
Jellyfin DLNA missing media

### ISSUE THREAD

**Issue by commedia-player** [commedia-player/Commedia#1]
@Nullcaller
> You can browse the directory structure, but folders display no media.
> It appears it's caused by Commedia not liking ampersands in media URIs. More info can be found here: 
> [https://github.com/jellyfin/jellyfin-plugin-dlna/issues/87](https://github.com/jellyfin/jellyfin-plugin-dlna/issues/87)

**Comment by commedia-player** [comment]
Fix is live on [Beta v0.2.2](https://www.meta.com/s/jtbFkCvv8).

**Comment by Nullcaller** [comment]
The fix works, thank you so much!

**Comment by commedia-player** [comment]
Released in Commedia v0.2.2
